# Generated by Django 4.1.3 on 2022-12-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pets", "0003_alter_pet_group_alter_pet_traits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pet",
            name="group",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="traits",
        ),
    ]
