# Generated by Django 4.1.3 on 2022-12-02 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("groups", "0004_remove_group_pet"),
        ("traits", "0004_remove_trait_pets"),
        ("pets", "0004_remove_pet_group_remove_pet_traits"),
    ]

    operations = [
        migrations.AddField(
            model_name="pet",
            name="group",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pets",
                to="groups.group",
            ),
        ),
        migrations.AddField(
            model_name="pet",
            name="traits",
            field=models.ManyToManyField(
                default=None, related_name="pets", to="traits.trait"
            ),
        ),
    ]
